---

services:
    kavita:
      image: jvmilazz0/kavita:latest
      container_name: kavita
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kavita.rule=Host(`${EBOOK_WEBSITE}`)"
        - "traefik.http.routers.kavita.entrypoints=https"
        - "traefik.http.routers.kavita.tls=true"
        - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      environment:
        - PUID=${APPUSER_PUID}
        - PGID=${APPUSER_PGID}
        - TZ=${TIME_ZONE_VALUE}
      volumes:
        #- ./manga:/manga
        - ${PATH_TO_EBOOKS}/Comics:/comics
        - ${PATH_TO_EBOOKS}/Books:/books
        - ${PATH_TO_DOCKERDATA}/kavita:/kavita/config
      #ports:
      #  - 5000:5000 # Change the public port (the first 5000) if you have conflicts with other services
      networks:
        - web
      restart: unless-stopped

networks:
  web:
    external: true