---

services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic-advanced.rule=Host(`${MUSIC_WEBSITE}`)"
      - "traefik.http.routers.airsonic-advanced.entrypoints=https"
      - "traefik.http.routers.airsonic-advanced.tls=true"
      - "traefik.http.services.airsonic-advanced.loadbalancer.server.port=4040"
    environment:
      - PUID=${APPUSER_PUID}
      - PGID=${APPUSER_PGID}
      - TZ=${TIME_ZONE_VALUE}
    volumes:
      - ${PATH_TO_MUSIC}:/music
      - ${PATH_TO_DOCKERDATA}/airsonic:/config
      - ${PATH_TO_DOCKERDATA}/airsonic/playlists:/playlists
      - ${PATH_TO_DOCKERDATA}/airsonic/podcasts:/podcasts
    #ports:
    #  - 4040:4040
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true