---

services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      - PUID=${APPUSER_PUID}
      - PGID=${APPUSER_PGID}
      - TZ=${TIME_ZONE_VALUE}
    volumes:
      - ${PATH_TO_MUSIC}:/music
      - ${PATH_TO_DOCKERDATA}/airsonic:/config
      - ${PATH_TO_DOCKERDATA}/airsonic/playlists:/playlists
      - ${PATH_TO_DOCKERDATA}/airsonic/podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped